version: '3'

services:
  backend:
    build: ./Backend   
    ports:
      - 5000:5000    
    volumes:
      - ./Backend/db:/db 
    environment:
      - DATABASE_URL=sqlite3:///db/dev.db
      - BACKEND_URL=http://backend:5000
    command: npm start --host 192.168.1.205
  frontend:
    build: ./FrontEnd/GameQuest   
    ports:
      - 5173:5173
    volumes:
    - ./frontend:/app
    - ./frontend/.env:/app/.env    
    depends_on:
      - backend 